### ISSUE TITLE
Notifications on "urgent" labels

### ISSUE THREAD

**Issue by mattcaswell** [openssl/tools#53]
Addition of labels doesn't result in a notification being sent out. It would be good if we sent out a notification when an urgent label has been applied to a PR

**Comment by iamamoose** [comment]
Do you want that to go out by email or a github comment notification?  if the latter then the logic could be:

If a PR has label: urgent and there hasn't been any other comment added to that PR since that label was assigned then create a comment mentioning (assignee/creator users) (or all of OTC?) [for example it could include [AT]openssl/otc  [AT]openssl/omc]

**Comment by mattcaswell** [comment]
Github comment notification seems fine. Your suggestion seems sensible.
